import { RowData } from './types/rowData';

export const GetData = (): RowData[] => [
    { id: 1, make: 'Tesla', model: 'Model Y', price: 64950, electric: true },
    { id: 2, make: 'Ford', model: 'F-Series', price: 33850, electric: false },
    { id: 3, make: 'Toyota', model: 'Corolla', price: 29600, electric: false },
    { id: 4, make: 'Mercedes', model: 'EQA', price: 48890, electric: true },
    { id: 5, make: 'Fiat', model: '500', price: 15774, electric: false },
    { id: 6, make: 'Nissan', model: 'Juke', price: 20675, electric: false },
    { id: 7, make: 'Vauxhall', model: 'Corsa', price: 18460, electric: false },
    { id: 8, make: 'Volvo', model: 'EX30', price: 33795, electric: true },
    { id: 9, make: 'Mercedes', model: 'Maybach', price: 175720, electric: false },
    { id: 10, make: 'Vauxhall', model: 'Astra', price: 25795, electric: false },
    { id: 11, make: 'Fiat', model: 'Panda', price: 13724, electric: false },
    { id: 12, make: 'Jaguar', model: 'I-PACE', price: 69425, electric: true },
    { id: 13, make: 'Tesla', model: 'Model Y', price: 64950, electric: true },
    { id: 14, make: 'Ford', model: 'F-Series', price: 33850, electric: false },
    { id: 15, make: 'Toyota', model: 'Corolla', price: 29600, electric: false },
    { id: 16, make: 'Mercedes', model: 'EQA', price: 48890, electric: true },
    { id: 17, make: 'Fiat', model: '500', price: 15774, electric: false },
    { id: 18, make: 'Nissan', model: 'Juke', price: 20675, electric: false },
    { id: 19, make: 'Vauxhall', model: 'Corsa', price: 18460, electric: false },
    { id: 20, make: 'Volvo', model: 'EX30', price: 33795, electric: true },
    { id: 21, make: 'Mercedes', model: 'Maybach', price: 175720, electric: false },
    { id: 22, make: 'Vauxhall', model: 'Astra', price: 25795, electric: false },
    { id: 23, make: 'Fiat', model: 'Panda', price: 13724, electric: false },
    { id: 24, make: 'Jaguar', model: 'I-PACE', price: 69425, electric: true },
    { id: 25, make: 'Tesla', model: 'Model Y', price: 64950, electric: true },
    { id: 26, make: 'Ford', model: 'F-Series', price: 33850, electric: false },
    { id: 27, make: 'Toyota', model: 'Corolla', price: 29600, electric: false },
    { id: 28, make: 'Mercedes', model: 'EQA', price: 48890, electric: true },
    { id: 29, make: 'Fiat', model: '500', price: 15774, electric: false },
    { id: 30, make: 'Nissan', model: 'Juke', price: 20675, electric: false },
    { id: 31, make: 'Vauxhall', model: 'Corsa', price: 18460, electric: false },
    { id: 32, make: 'Volvo', model: 'EX30', price: 33795, electric: true },
    { id: 33, make: 'Mercedes', model: 'Maybach', price: 175720, electric: false },
    { id: 34, make: 'Vauxhall', model: 'Astra', price: 25795, electric: false },
    { id: 35, make: 'Fiat', model: 'Panda', price: 13724, electric: false },
    { id: 36, make: 'Jaguar', model: 'I-PACE', price: 69425, electric: true },
  ];